FROM 851725599256.dkr.ecr.ap-south-1.amazonaws.com/base

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
#checking code changes
COPY . .
EXPOSE 5000
CMD ["python", "app.py"]

